version: '3.7'

services:
  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=s3
    ports:
      - "4572:4572"
    volumes:
      - ./initaws:/docker-entrypoint-initaws.d
